version: "2"
services:
  mounted-test:
      image: alpine
      container_name: 'docker-mount'
      volumes:
        - .:/test:rw
      command: /bin/sh -c "cd test && time dd if=/dev/zero of=test.dat bs=1024 count=100000"